// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/flexi/calculate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/flexi/calculate.post').default>>>>
    }
    '/api/products': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products.post').default>>>>
    }
    '/api/segment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/segment.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}