// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/7/2026, 8:12:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/plugins/**/*.{js,ts,mjs}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/stores/**/*.{js,ts,mjs}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/composables/**/*.{js,ts,mjs}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/utils/**/*.{js,ts,mjs}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/constants/**/*.{js,ts,mjs}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/suppawit.folk/Documents/ProjectBLA/product-recommend-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;